# Generated by Django 5.0.3 on 2024-03-28 11:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
    ]
