# Generated by Django 5.0.3 on 2024-03-28 11:35

import customer_support.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('', '-- please choose --'), ('billing', 'billing and payments'), ('bugs', 'report a bug'), ('contact', 'contact request'), ('other', 'everything else')], default='', max_length=50, verbose_name='subject')),
                ('body', models.TextField(blank=True, default='', max_length=10000, verbose_name='body')),
                ('sender_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name')),
                ('sender_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('status', models.CharField(choices=[('new', 'new'), ('read', 'read'), ('processing', 'processing'), ('closed', 'closed')], db_index=True, default='new', max_length=15, verbose_name='status')),
                ('access_key', models.CharField(default=customer_support.models.get_access_key, max_length=42, verbose_name='access key')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', max_length=10000, verbose_name='body')),
                ('sender_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name')),
                ('sender_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('recipient_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name')),
                ('recipient_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_support.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket message',
                'verbose_name_plural': 'ticket messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
